packages: []

blockExoticSubdeps: true
minimumReleaseAge: 10080 # 7 days

allowBuilds:
  "@parcel/watcher": false
  esbuild: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  # Renovate security update: next@16.3.8
  - next@16.3.6 || 16.3.8
