name: Docker update Staging

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  docker-build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/docker-build.yml
    with:
      ACCOUNT_ID: ${{ vars.STAGING_AWS_ACCOUNT_ID }}
      GITHUB_SHA: ${{ github.sha }}
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

  docker-deploy:
    needs: docker-build
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/docker-deploy.yml
    with:
      ACCOUNT_ID: ${{ vars.STAGING_AWS_ACCOUNT_ID }}
      GITHUB_SHA: ${{ github.sha }}
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

  docker-sbom:
    needs: docker-build
    permissions:
      contents: write
    uses: ./.github/workflows/docker-sbom.yml
    with:
      GITHUB_SHA: ${{ github.sha }}
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

  integration-test:
    needs: docker-deploy
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/integration-test.yml
    with:
      account_id: ${{ vars.STAGING_AWS_ACCOUNT_ID }}
      bucket_name: ${{ vars.STAGING_INTEGRATION_TEST_BUCKET_NAME }}
      idp_url: ${{ vars.STAGING_INTEGRATION_TEST_IDP_URL }}
      portal_url: ${{ vars.STAGING_INTEGRATION_TEST_PORTAL_URL }}
    secrets:
      log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
      username: ${{ secrets.STAGING_INTEGRATION_TEST_USERNAME }}
      password: ${{ secrets.STAGING_INTEGRATION_TEST_PASSWORD }}
      totp_secret: ${{ secrets.STAGING_INTEGRATION_TEST_TOTP_SECRET }}
      waf_geo_restriction_bypass: ${{ secrets.STAGING_WAF_GEO_RESTRICTION_BYPASS }}
      zitadel_bearer_token: ${{ secrets.STAGING_INTEGRATION_TEST_ZITADEL_BEARER_TOKEN }}
      
  workflow-failure:
    needs: 
      - docker-build
      - docker-deploy
      - docker-sbom
      - integration-test
    if: >-
      always() && (
        needs.docker-build.result == 'failure' ||
        needs.docker-deploy.result == 'failure' ||
        needs.integration-test.result == 'failure'
      )
    permissions: {}
    uses: ./.github/workflows/workflow-failure.yml
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAGING_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}
