name: Docker PR

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}

permissions: {}

jobs:
  docker-pr:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - image: idp-login
            directory: .
          - image: idp-load-test
            directory: ./test/perf

    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Docker build
        working-directory: ${{ matrix.directory }}
        run: |
          docker build \
            --platform linux/arm64 \
            --build-arg GIT_SHA=$GITHUB_SHA \
            --tag ${{ matrix.image }}:latest \
            .
