name: Integration Test Production

concurrency:
  group: docker-update-production
  cancel-in-progress: false

on:
  repository_dispatch:
    types:
      - integration-test-production

permissions: {}

jobs:
  integration-test:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/integration-test.yml
    with:
      account_id: ${{ vars.PROD_AWS_ACCOUNT_ID }}
      bucket_name: ${{ vars.PROD_INTEGRATION_TEST_BUCKET_NAME }}
      idp_url: ${{ vars.PROD_INTEGRATION_TEST_IDP_URL }}
      portal_url: ${{ vars.PROD_INTEGRATION_TEST_PORTAL_URL }}
      test_command: "test:playwright:smoke"
    secrets:
      log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
      register_email: ${{ secrets.PROD_INTEGRATION_TEST_REGISTER_EMAIL }}
      username: ${{ secrets.PROD_INTEGRATION_TEST_USERNAME }}
      password: ${{ secrets.PROD_INTEGRATION_TEST_PASSWORD }}
      test_callback_url: ${{ secrets.PROD_INTEGRATION_TEST_CALLBACK_URL }}
      test_client_id: ${{ secrets.PROD_INTEGRATION_TEST_CLIENT_ID }}
      totp_secret: ${{ secrets.PROD_INTEGRATION_TEST_TOTP_SECRET }}
      zitadel_service_account_key: ${{ secrets.PROD_INTEGRATION_TEST_ZITADEL_SERVICE_ACCOUNT_KEY }}

  workflow-failure:
    needs:
      - integration-test
    if: failure()
    permissions: {}
    uses: ./.github/workflows/workflow-failure.yml
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.PROD_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}
